version: 2

project_name: asd-brightness-daemon

builds:
  - id: asd-brightness-daemon
    dir: daemon
    main: ./cmd/asd-brightness-daemon
    binary: asd-brightness-daemon
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1

nfpms:
  - id: deb-package
    package_name: asd-brightness
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - asd-brightness-daemon
    vendor: shini4i
    maintainer: "Vadim Gedz <github@shini4i.dev>"
    description: "Apple Studio Display Brightness Control for GNOME"
    license: GPL-3.0
    formats:
      - deb
    dependencies:
      - gnome-shell
      - libhidapi-hidraw0
    contents: &package-contents
      - src: ./packaging/systemd/user/asd-brightness.service
        dst: /usr/lib/systemd/user/asd-brightness.service
        file_info:
          mode: 0644
      - src: ./packaging/rules.d/90-apple-studio-display.rules
        dst: /etc/udev/rules.d/90-apple-studio-display.rules
        file_info:
          mode: 0644
      - src: ./extension/
        dst: /usr/share/gnome-shell/extensions/asd-brightness@shini4i.github.io/
    scripts: &package-scripts
      postinstall: ./packaging/scripts/postinstall.sh
      preremove: ./packaging/scripts/preremove.sh

  - id: rpm-package
    package_name: asd-brightness
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - asd-brightness-daemon
    vendor: shini4i
    maintainer: "Vadim Gedz <github@shini4i.dev>"
    description: "Apple Studio Display Brightness Control for GNOME"
    license: GPL-3.0
    formats:
      - rpm
    dependencies:
      - gnome-shell
      - hidapi
    contents: *package-contents
    scripts: *package-scripts

changelog:
  use: github-native

release:
  github:
    owner: shini4i
    name: gnome-shell-extension-apple-studio-display
  draft: false
  prerelease: auto
