// Code generated by MockGen. DO NOT EDIT.
// Source: internal/hid/device.go
//
// Generated by this command:
//
//	mockgen -source=internal/hid/device.go -destination=internal/hid/mocks/device_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	hid "github.com/shini4i/asd-brightness-daemon/internal/hid"
	gomock "go.uber.org/mock/gomock"
)

// MockDevice is a mock of Device interface.
type MockDevice struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceMockRecorder
	isgomock struct{}
}

// MockDeviceMockRecorder is the mock recorder for MockDevice.
type MockDeviceMockRecorder struct {
	mock *MockDevice
}

// NewMockDevice creates a new mock instance.
func NewMockDevice(ctrl *gomock.Controller) *MockDevice {
	mock := &MockDevice{ctrl: ctrl}
	mock.recorder = &MockDeviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDevice) EXPECT() *MockDeviceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDevice) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDeviceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDevice)(nil).Close))
}

// GetFeatureReport mocks base method.
func (m *MockDevice) GetFeatureReport(data []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFeatureReport", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFeatureReport indicates an expected call of GetFeatureReport.
func (mr *MockDeviceMockRecorder) GetFeatureReport(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFeatureReport", reflect.TypeOf((*MockDevice)(nil).GetFeatureReport), data)
}

// Info mocks base method.
func (m *MockDevice) Info() hid.DeviceInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info")
	ret0, _ := ret[0].(hid.DeviceInfo)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockDeviceMockRecorder) Info() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockDevice)(nil).Info))
}

// SendFeatureReport mocks base method.
func (m *MockDevice) SendFeatureReport(data []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFeatureReport", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendFeatureReport indicates an expected call of SendFeatureReport.
func (mr *MockDeviceMockRecorder) SendFeatureReport(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFeatureReport", reflect.TypeOf((*MockDevice)(nil).SendFeatureReport), data)
}
